=== factor5/j-timetracker/TimeTracker/dataStore.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="dataStore">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="timer" />
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:element name="timer">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="timerName" type="xs:string" />
				<xs:element name="notes" type="xs:string" />
				<xs:element name="dateCreated" type="xs:string" />
				<xs:element ref="elapsedTime" />
			</xs:sequence>
			<xs:attribute name="id" use="required" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="elapsedTime">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="days" type="xs:string" />
				<xs:element name="hours" type="xs:string" />
				<xs:element name="minutes" type="xs:string" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== factor5/j-timetracker/TimeTracker/dataStore.xml
<?xml version="1.0" encoding="UTF-8"?>

<dataStore xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="dataStore.xsd">
	
	<timer id="1">
		<timerName>First timer name</timerName>
		<notes>ala bala</notes>
		<dateCreated></dateCreated>
		<elapsedTime>
			<days>00</days>
			<hours>01</hours>
			<minutes>23</minutes>
		</elapsedTime>
	</timer>
	<timer id="2">
		<timerName>Second timer name</timerName>
		<notes>maleee</notes>
		<dateCreated></dateCreated>
		<elapsedTime>
			<days>12</days>
			<hours>02</hours>
			<minutes>12</minutes>
		</elapsedTime>
	</timer>
	<timer id="3">
		<timerName>Third timer name</timerName>
		<notes>drun drun</notes>
		<dateCreated></dateCreated>
		<elapsedTime>
			<days>00</days>
			<hours>11</hours>
			<minutes>01</minutes>
		</elapsedTime>
	</timer>
	
</dataStore>

=== factor5/j-timetracker/trunk/TimeTracker/dataStore-1.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataStore xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="dataStore.xsd">
	<timer id="2">
		<timerName>timer2</timerName>
		<notes>ala bala 222</notes>
		<dateCreated>Wed Dec 29 00:56:31 EET 2010</dateCreated>
		<elapsedTime>
			<days>2</days>
			<hours>2</hours>
			<minutes>2</minutes>
		</elapsedTime>
	</timer>
	<timer id="1">
		<timerName>timer1</timerName>
		<notes>ala bala</notes>
		<dateCreated>Wed Dec 29 00:56:31 EET 2010</dateCreated>
		<elapsedTime>
			<days>1</days>
			<hours>5</hours>
			<minutes>23</minutes>
		</elapsedTime>
	</timer>
</dataStore>
